# Wir nutzen das offizielle AppDaemon-Image als Basis
FROM acockburn/appdaemon:latest

# Optional: Falls du zusätzliche Pakete installieren willst, kannst du das hier tun, z. B.:
# RUN pip install some_package

# Starte AppDaemon und nutze /config/appdaemon als Konfig-Verzeichnis
CMD [ "appdaemon", "-c", "/config/appdaemon" ]
